version: '3.1'
services:
  db:
    image: postgres:latest
    ports:
    - '5432:5432'
    environment:
      POSTGRES_USER: 'pairings'
      POSTGRES_PASSWORD: 'pairings'
      POSTGRES_DB: 'pairings'
    networks:
      - pairings_network
networks:
  pairings_network:
    driver: bridge
